// Copies the assets the game uses from the web repo into ./assets and writes
// src/assets/manifest.ts (static requires, so Metro bundles them).
//
//   node scripts/build-assets.mjs [path/to/opus-creative-htmls/assets]
//
// - GLBs are copied as-is. They reference their kit's Textures/colormap.png,
//   which the runtime serves from the matching raw texture (see engine/assets.ts).
// - PNGs (kit colormaps, particle sprites) become raw RGBA: 8-byte header
//   (uint32 LE width, height) + pixels, top row first. No image decoder needed on device.
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';
import { ALL_MODELS, PARTICLES } from '../src/game/config.ts';

const root = path.resolve(import.meta.dirname, '..');
const src = path.resolve(process.argv[2] ?? path.join(root, '../emredardagan/opus-creative-htmls/assets'));
const out = path.join(root, 'assets');
if (!fs.existsSync(path.join(src, 'kenney'))) throw new Error(`No kenney/ folder in ${src}`);

fs.rmSync(path.join(out, 'models'), { recursive: true, force: true });
fs.rmSync(path.join(out, 'textures'), { recursive: true, force: true });
fs.mkdirSync(path.join(out, 'textures'), { recursive: true });

const kits = new Set();
const lines = [];
for (const key of ALL_MODELS) {
  const from = path.join(src, 'kenney', `${key}.glb`);
  if (!fs.existsSync(from)) throw new Error(`Missing model ${from}`);
  const to = path.join(out, 'models', `${key}.glb`);
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
  // which external images does it point at?
  const b = fs.readFileSync(from);
  const json = JSON.parse(b.subarray(20, 20 + b.readUInt32LE(12)).toString());
  for (const img of json.images ?? []) {
    if (img.uri !== 'Textures/colormap.png') throw new Error(`${key}: unexpected image ${JSON.stringify(img)}`);
    kits.add(key.split('/')[0]);
  }
  lines.push(`  '${key}': require('../../assets/models/${key}.glb'),`);
}

async function raw(file, to, size) {
  let img = sharp(file).ensureAlpha();
  if (size) img = img.resize(size, size);
  const { data, info } = await img.raw().toBuffer({ resolveWithObject: true });
  const head = Buffer.alloc(8);
  head.writeUInt32LE(info.width, 0); head.writeUInt32LE(info.height, 4);
  fs.writeFileSync(to, Buffer.concat([head, data]));
  return info;
}

const texLines = [];
for (const kit of [...kits].sort()) {
  const info = await raw(path.join(src, 'kenney', kit, 'Textures/colormap.png'), path.join(out, 'textures', `colormap-${kit}.bin`));
  texLines.push(`  '${kit}': require('../../assets/textures/colormap-${kit}.bin'), // ${info.width}x${info.height}`);
}
const partLines = [];
for (const name of PARTICLES) {
  await raw(path.join(src, 'kenney/particles', `${name}.png`), path.join(out, 'textures', `particle-${name}.bin`), 128);
  partLines.push(`  '${name}': require('../../assets/textures/particle-${name}.bin'),`);
}
fs.mkdirSync(path.join(out, 'hdri'), { recursive: true });
fs.copyFileSync(path.join(src, 'hdri/kloofendal_puresky_1k.hdr'), path.join(out, 'hdri/sky.hdr'));

// licenses travel with the assets
fs.mkdirSync(path.join(out, 'licenses'), { recursive: true });
fs.copyFileSync(path.join(src, 'hdri/LICENSE.txt'), path.join(out, 'licenses/polyhaven-LICENSE.txt'));
fs.copyFileSync(path.join(src, 'kenney/cube-pets/License.txt'), path.join(out, 'licenses/kenney-License.txt'));

fs.writeFileSync(path.join(root, 'src/assets/manifest.ts'), `// Generated by scripts/build-assets.mjs. Do not edit.
/* eslint-disable */
export const MODELS: Record<string, number> = {
${lines.join('\n')}
};

export const COLORMAPS: Record<string, number> = {
${texLines.join('\n')}
};

export const PARTICLE_TEXTURES: Record<string, number> = {
${partLines.join('\n')}
};

export const SKY_HDR: number = require('../../assets/hdri/sky.hdr');
`);
console.log(`${ALL_MODELS.length} models, ${kits.size} colormaps, ${PARTICLES.length} particles`);
